service:
  group: test-group
  name: test-service
  version: 0.1.0

api:
  endpoint:
    port: 7777
    baseRoutingPath: /api/v1
  security:
    enabled: true
    jwt:
      secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      expiration:
        enabled: true
        minutes: 13149000

client:
  timeout: 120s
  dialerTimeout: 2s
  tlsHandshakeTimeout: 10s
  expectContinueTimeout: 4s
  responseHeaderTimeout: 10s
  balancing:
    strategy: round-robin
  serviceRegistry:
    type: sgulreg
    url: http://localhost:9687
    fallback:
    - http://localhost:5557/api/v1
    - http://localhost:5558/api/v1

db:
  type: mysql
  host: localhost
  port: 3306
  user: xxxxxx
  password: yyyyyy
  database: zzzzzz
  log: false
  migrations:
    enabled: true
    drop: true
    singularTableNames: true
